%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Load and organize prosthetic group data
dat = readtable('../../ComplementaryData/biomass/prosthetic_groups_uniProt.txt',...
    'ReadVariableNames',0);

pGroups.genes   = table2array(dat(2:end,1));
pGroups.mets    = transpose(table2array(dat(1,2:end)));
pGroups.S       = str2double(table2array(dat(2:end,2:end)));
clear dat

%% Distribute "metal" and discard dipyrromethane
allMetals           = contains(pGroups.mets,{'cobalt2_c','cu2_c','fe2_c',...
    'zn2_c','ni2_c','ca2_c','k_c','mg2_c','mn2_c'});
allMetals           = allMetals./sum(allMetals);

metalIdx            = strcmp(pGroups.mets,'metal');
metal               = find(pGroups.S(:,metalIdx));
pGroups.S(metal,:)  = pGroups.S(metal,:) + ...
                        transpose(repmat(allMetals,1,length(metal)));
pGroups.S(:,metalIdx)   = [];
pGroups.mets(metalIdx)  = [];

% Dipyrromethane is generated by the enzyme itself from its substrate
dpmIdx              = strcmp(pGroups.mets,'dpm');
pGroups.S(:,dpmIdx)	= [];
pGroups.mets(dpmIdx)= [];

%% Load and organize proteomics data
cd ../ecModel/
[prot.data, ~, prot.genes] = prepareProteomicsM1152M145;
prot.mean           = mean(prot.data,2,'omitnan');
[Lia, Locb]         = ismember(pGroups.genes,prot.genes);
pGroups.mmol        = zeros(length(pGroups.genes),1)
pGroups.mmol(Lia)   = prot.mean(Locb(Lia));

clear dat
cd ../consensusModel/

%% Calculate abundances
pGroups.coeffs = transpose(pGroups.S) * pGroups.mmol;
out = pGroups.mets;
out(:,2) = cellstr(num2str(pGroups.coeffs,'%s'));
out = table(out(:,1),out(:,2),'VariableNames',{'mets';'coeffs'});
writetable(out,'../../ComplementaryData/biomass/prosthetic_groups_mets.txt','Delimiter','\t');
